spring:
  application:
    name: som
  main:
    allow-bean-definition-overriding: true # aynı bean ismi ile bean oluşturulabilir.
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/turkcell-soccer-online-managemanetdb
    password: '12345'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
server:
  port: 8090
application:
  security:
    jwt:
      secret-key: 1cc545c907bb8122cdd3d5feec5d5e5062db82bebe5c83eab114a33aaf9536c2 # 256 bit secret key



